#!/bin/sh
docker run \
  --rm \
  -i \
  --user "$(id -u):$(id -g)" \
  -e AWS_CONFIG_FILE=/tmp/.aws/config \
  -e AWS_SHARED_CREDENTIALS_FILE=/tmp/.aws/credentials \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  -v "$HOME/.aws:/tmp/.aws:rw" \
  -v $(pwd):/aws \
  amazon/aws-cli $@
