#!/bin/sh
docker run \
  --rm \
  --user "$(id -u):$(id -g)" \
  -e AWS_CONFIG_FILE=/tmp/.aws/config \
  -e AWS_SHARED_CREDENTIALS_FILE=/tmp/.aws/credentials \
  -v "$HOME/.aws:/tmp/.aws:rw" \
  -v $(pwd):/aws \
  amazon/aws-cli $@
